version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: cpan228-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cpan228qa
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: cpan228-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: qa
    restart: always

volumes:
  mysql-data: